# Generated by Django 5.1.6 on 2025-02-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('employee_type', models.CharField(choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse')], default='Doctor', max_length=10)),
            ],
        ),
    ]
