# Generated by Django 5.1.6 on 2025-02-16 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_patient_gender_alter_patient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'employee_type': 'Doctor'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.employee'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.patient'),
        ),
    ]
